Add knex-db-manager to truncate tables in test runs

diff --git a/scripts/resetTestDatabase b/scripts/resetTestDatabase
--- a/scripts/resetTestDatabase
+++ b/scripts/resetTestDatabase
@@ -6,7 +6,7 @@ DBNAME=pjtest
 
 # drop the database
 echo "Dropping database $DBNAME"
-docker-compose exec -u postgres db dropdb $DBNAME || { echo "Error dropping database" ; exit 1; }
+docker-compose exec -u postgres db dropdb --if-exists $DBNAME || { echo "Error dropping database" ; exit 1; }
 
 # create the database
 echo "Creating database $DBNAME"
